update `show` set warningText="Strong Language, Mature Themes" where name="1 Hour";
update `show` set warningText="Shadowy Nightmare Fuel" where name="13 Dead Dreams of \"Eugene\"";
update `show` set warningText="Sexual References, Drug References, Violence Descriptions" where name="6 Quick Dick Tricks: A Dirk Darrow Investigation";
update `show` set warningText="Strong Language" where name="A Canadian Bartender at Butlin\'s";
update `show` set warningText="" where name="A Solo from the Pit (Second Trombone\'s Voice)";
update `show` set warningText="" where name="Almost, Maine";
update `show` set warningText="" where name="Along The Way";
update `show` set warningText="Mature Themes" where name="Amok Monologues: All Pucked Up";
update `show` set warningText="Strong Language" where name="An All New God Is A Scottish Drag Queen";
update `show` set warningText="Strong Language, Mature Themes" where name="An Excruciatingly Ordinary Toy Theater Show";
update `show` set warningText="Mild Language, Frank talk of Death, Violence, Religion" where name="Anatomy of Gray";
update `show` set warningText="Nudity, Mature Themes" where name="Apt 2C";
update `show` set warningText="" where name="AQUAdance";
update `show` set warningText="Mature Themes" where name="Awake";
update `show` set warningText="Strong Language" where name="Banned In The USA";
update `show` set warningText="Mature Themes" where name="Becoming Magic Mike: An Action Adventure Comedy";
update `show` set warningText="Mature Themes, Some Language" where name="Beneath the Bikini";
update `show` set warningText="Strong Language, Nudity" where name="Black Crow Cabaret";
update `show` set warningText="" where name="Bloke and Swagger";
update `show` set warningText="Sexual Themes, Threatened Gun Violence" where name="Blonde";
update `show` set warningText="Mature Themes" where name="BlueStar Presents: VarieTEASE... SpellBound";
update `show` set warningText="" where name="Buggin\' Out: A Small Musical";
update `show` set warningText="" where name="BUSHEL AND PECK";
update `show` set warningText="Strong Language, Mature Themes" where name="California Kiki";
update `show` set warningText="Strong Language" where name="Callbacks";
update `show` set warningText="Language, Violence, Religion, Frank Talk of Death" where name="Chamber Music";
update `show` set warningText="Strong Language" where name="Chris Turner: Turner\'s Masterpieces";
update `show` set warningText="Mild Language" where name="Collected Stories";
update `show` set warningText="Mature Themes, Nudity, Crude Humor" where name="Corsets & Cuties - Harlots";
update `show` set warningText="Strong Language, Mature Themes" where name="Dammit, Jim! I\'m a Comedienne, Not a Doctor!";
update `show` set warningText="" where name="DAYBREAK- The Musical Documentary of John Delaney";
update `show` set warningText="Strong Language, Mature Themes, Violence" where name="Dead For A Ducat";
update `show` set warningText="Adult Themes" where name="Death Part 7: The Last Word";
update `show` set warningText="Strong Language, Mature Themes" where name="Disenchanted!";
update `show` set warningText="Disturbing Imagery" where name="Eddie Poe";
update `show` set warningText="" where name="El Wiz";
update `show` set warningText="Mature Themes" where name="Eleanor\'s Story: An American Girl In Hitler\'s Germany";
update `show` set warningText="Some PG-13 Language" where name="Enter, Pursued By a Whale";
update `show` set warningText="" where name="Fallen from the Toy Box";
update `show` set warningText="" where name="Falling Awake";
update `show` set warningText="Strong Language, Mature Themes" where name="F*ckboys: The Musical";
update `show` set warningText="Adult Language, Mature Themes" where name="FLIP";
update `show` set warningText="Mature Themes" where name="Flori-DUH";
update `show` set warningText="Strong Language, Substance Abuse, Mature Themes" where name="Fool\'s Gold";
update `show` set warningText="Strong Language, Mature Themes, Discussion of Violence" where name="For Love, Sir: Letters of Life, Love, and Sacrifice";
update `show` set warningText="Strong Language, Mature Themes" where name="Forgotten Memoirs";
update `show` set warningText="Innuendo, Mild Language" where name="Fringe Family Feud";
update `show` set warningText="Strong Language, Mature Themes, Interspecies Relationships" where name="FROGPIG";
update `show` set warningText="Mature Theme" where name="Ghosts Among Us";
update `show` set warningText="Adult Situations, Adult Language, and more Adult Situations" where name="God Bless Cambodia";
update `show` set warningText="Strong Language" where name="Gorgeous";
update `show` set warningText="Strong Language, Mature Themes" where name="HELLO";
update `show` set warningText="" where name="Hot Dog!";
update `show` set warningText="Strong Language" where name="I Think I\'m Dead";
update `show` set warningText="Strong Language, Mature Themes" where name="In Search Of Cruise Control";
update `show` set warningText="" where name="In Tandem";
update `show` set warningText="Mature Themes" where name="Jack Kerouac - End of the Road";
update `show` set warningText="" where name="James & Jamesy in the Dark";
update `show` set warningText="" where name="Jason & the Argonauts";
update `show` set warningText="Strong Language, Mature Themes" where name="Jealousy";
update `show` set warningText="Strong Language, Mature Themes, Nudity" where name="Jon Bennett: Fire in the Meth Lab";
update `show` set warningText="Mature Themes, Nudity" where name="Keep It Gay";
update `show` set warningText="Strong Language, Mature Themes" where name="Kevin, King of Egypt";
update `show` set warningText="Mature Themes, Gender Bending, Strong Language, Nudity" where name="LadyBoys of The Peek-A-Boo Lounge";
update `show` set warningText="Strong Language, Mature Themes" where name="Lauren & Amanda Do It";
update `show` set warningText="" where name="Love is Love";
update `show` set warningText="" where name="LUNA";
update `show` set warningText="Profanity" where name="Mar\'keyth the Bar\'keep";
update `show` set warningText="Mature Themes" where name="Mason, Son of Ma";
update `show` set warningText="Mature Themes, Strong Language" where name="Meet The Replacements";
update `show` set warningText="Mature Themes" where name="Mike Delamont: Husky Panda";
update `show` set warningText="News Radio Clips from NPR" where name="Mindful Momentum: Praying to Cars";
update `show` set warningText="Strong Language, Violence" where name="Mo-to-the-oncle";
update `show` set warningText="Some Language, Mature Themes" where name="Moth";
update `show` set warningText="Mature Themes, Partial Nudity" where name="Mozart & Marie";
update `show` set warningText="Mature Themes, Nudity, Sexual Content" where name="MULTIPLE ORGANISM";
update `show` set warningText="Some Language" where name="MUTTNIK";
update `show` set warningText="Language, Mature Themes" where name="My Pal Bette";
update `show` set warningText="Language, Mature Themes" where name="Nashville Hurricane";
update `show` set warningText="Foul Language" where name="Nicky\'s Solo Improvised Musical";
update `show` set warningText="Strong Language" where name="ODAT: Fighting Cancer One Day At  A Time";
update `show` set warningText="Mature Themes, Strong Language" where name="\"Oh, Hi Johnny\" The Roomsical Parody Musical";
update `show` set warningText="" where name="One Man Pride and Prejudice";
update `show` set warningText="Strong Language" where name="One Man Stranger Things: A Parody";
update `show` set warningText="Strong Language, Mature Themes, Cartoonish Violence" where name="One Man Walking Dead";
update `show` set warningText="Strong Language" where name="Orlando Fringe Presents: National and International Artists Teaser Show";
update `show` set warningText="" where name="Orlando Fringe Presents: One Man Star Wars Trilogy";
update `show` set warningText="Adult Shenanigans" where name="Orlando Fringe Presents: Tonight at Midnight with Rauce Padgett";
update `show` set warningText="Death, Strong Language, Interaction" where name="Patron\'s Pick...for Murder";
update `show` set warningText="Strong Language, Mature Themes, Sexual Content, Violence" where name="PeeVira\'s SCAREavan Sing-Along: Disney Addicktion";
update `show` set warningText="Strong Language, Mature Themes" where name="Pianos to the Death Game Show";
update `show` set warningText="Strong Language, Mature Themes" where name="Picasso At The Lapin Agile";
update `show` set warningText="Strong Language, Mature Themes" where name="Red Bastard: Lie With Me";
update `show` set warningText="" where name="Ruminations";
update `show` set warningText="Mature Themes" where name="Save me, Dolly Parton, by Megan Gogerty";
update `show` set warningText="Strong Language, Nudity, Violence, Sexual Content, Nasty Women" where name="SCUM: A Manifesto";
update `show` set warningText="Strong Language, Mature Themes" where name="Shadows in Bloom";
update `show` set warningText="Mature Theme" where name="Shakespeare\'s Ghostbusters";
update `show` set warningText="Strong Language, Mature Themes" where name="Shit I\'m in Love With You Again";
update `show` set warningText="Strong Language, Mature Themes, Violence" where name="S#IT: An Unauthorized Musical Parody of Stephen King\'s IT";
update `show` set warningText="Strong Language, Mature Themes" where name="Somebody\'s History";
update `show` set warningText="Language" where name="Stewart Huff: Critical Thinkin\'";
update `show` set warningText="" where name="Strange New Worlds";
update `show` set warningText="Mature Themes, Strong Language" where name="Tales of a Southern Belle";
update `show` set warningText="Mild Language" where name="Taurus Faeces";
update `show` set warningText="Strong Language, Mature Themes" where name="The Biscuiteater";
update `show` set warningText="Mature Themes, Langauge, Whips, Bondage" where name="The Companion and Safe Word";
update `show` set warningText="" where name="The Downtowners - LIVE!";
update `show` set warningText="Violence, Graphic Images" where name="The Encampment of Dr. Moreau";
update `show` set warningText="Strong Language" where name="The Gospel According to My Old Man";
update `show` set warningText="Adult Themes" where name="The Great & Powerful Tim Saves Christmas";
update `show` set warningText="Strong Language, Mature Themes" where name="The Haunting of Saint River";
update `show` set warningText="" where name="The Jurassic Parks";
update `show` set warningText="Adult Themes" where name="The Last Door";
update `show` set warningText="" where name="The Light Princess";
update `show` set warningText="Mildly Explicit Language and References" where name="The Sibyl of Mars";
update `show` set warningText="Strong Language, Mature Themes, Violence" where name="T.H.E.M (The Heroes Exemplifying Mediocrity)";
update `show` set warningText="Stronge Language, Mature Themes, Comedic Violence...the stuff you love on \"Game of Thrones\"" where name="Thrones! The Musical Parody";
update `show` set warningText="" where name="Thunderfoot";
update `show` set warningText="Strong Language" where name="Tim Mooney: Mancave";
update `show` set warningText="Mature Themes" where name="Title and Deed";
update `show` set warningText="" where name="TK 421 Is Dead: A Storm Trooper Story";
update `show` set warningText="Language" where name="to be happy.";
update `show` set warningText="Strong Language, Mature Themes" where name="Torment: The Musical";
update `show` set warningText="Nudity, Strong Language, Mature Themes" where name="Vampire Lesbians of Sodom";
update `show` set warningText="" where name="Van Gogh Find Yourself #vgfy";
update `show` set warningText="Adult Language and Themes" where name="WANZIE\'S MONORAIL INFERNO";
update `show` set warningText="Strong Language, Some Mature Content, Sexual Themes" where name="What If?";
update `show` set warningText="Language, Violence, Death, Frightening Images" where name="When the Hurly Burly\'s Done";
update `show` set warningText="" where name="Xanadu Jr";
